### ISSUE TITLE
MEMO field empty

### ISSUE THREAD

**Issue by ondohotola** [JeremyJones/Finance--OFX--Parse--Simple#4]
I have a reasonably well formed OFX and am trying to read it like so:

use Finance::OFX::Parse::Simple;
my $parser     = Finance::OFX::Parse::Simple->new;
my $ofxContent = $parser->parse_file("test.txt"); 

but find that the MEMO fields are empty.
[test.txt](https://github.com/JeremyJones/Finance--OFX--Parse--Simple/files/439724/test.txt)

Any idea how I would get the contents of the MEMO fields to display?

greetings, el

**Comment by JeremyJones** [comment]
The bug is due to the CDATA specifiers. 

```
	        my $memo = do
                {
                    my $w = "";
                    if ($s =~ m/<MEMO>([^\r\n<]+)/s)
                    {
     	                $w = $1;
                    }
                    $w;
                };
```

You can replace those lines above with this version, which finds those MEMO values ok:

```
                my $memo = do
                {
                    my $w = "";
                    if ($s =~ m/<MEMO>((?:[^\r\n<]|<(?!\/MEMO))+)/s)
	            {
                     	$w = $1;
                        $w =~ s/^<..CDATA.(.*)..>$/$1/s;
                    }
                    $w;
     	        };
```

Or you can patch Simple.pm with this diff:

```
158c158
<                   if ($s =~ m/<MEMO>([^\r\n<]+)/s)
---
>                   if ($s =~ m/<MEMO>((?:[^\r\n<]|<(?!\/MEMO))+)/s)
160a161
>                       $w =~ s/^<..CDATA.(.*)..>$/$1/s;

```
